// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AgentEvent struct {
	ID        AgentEventID   `json:"id"`
	AgentID   string         `json:"agent_id"`
	ProjectID NullProjectID  `json:"project_id"`
	StepID    NullStepID     `json:"step_id"`
	EventType EventType      `json:"event_type"`
	Timestamp SQLiteTime     `json:"timestamp"`
	Metadata  sql.NullString `json:"metadata"`
}

type Dependency struct {
	StepID          StepID `json:"step_id"`
	DependsOnStepID StepID `json:"depends_on_step_id"`
}

type FailedStepsHistory struct {
	ID             int64          `json:"id"`
	OriginalStepID StepID         `json:"original_step_id"`
	ProjectID      ProjectID      `json:"project_id"`
	StepNum        int64          `json:"step_num"`
	Branch         string         `json:"branch"`
	Scope          string         `json:"scope"`
	Worktree       sql.NullString `json:"worktree"`
	AgentID        sql.NullString `json:"agent_id"`
	ClaimedAt      NullSQLiteTime `json:"claimed_at"`
	StartedAt      NullSQLiteTime `json:"started_at"`
	FailedAt       NullSQLiteTime `json:"failed_at"`
	LastCommit     sql.NullString `json:"last_commit"`
	FilesModified  sql.NullString `json:"files_modified"`
	Notes          sql.NullString `json:"notes"`
	ArchivedAt     SQLiteTime     `json:"archived_at"`
}

type Project struct {
	ID         ProjectID      `json:"id"`
	Name       string         `json:"name"`
	BaseCommit sql.NullString `json:"base_commit"`
	CreatedAt  SQLiteTime     `json:"created_at"`
	Status     ProjectStatus  `json:"status"`
	Priority   int64          `json:"priority"`
}

type SchemaMigration struct {
	Version   int64  `json:"version"`
	AppliedAt string `json:"applied_at"`
}

type Step struct {
	ID            StepID         `json:"id"`
	ProjectID     ProjectID      `json:"project_id"`
	StepNum       int64          `json:"step_num"`
	Branch        string         `json:"branch"`
	Scope         string         `json:"scope"`
	Status        StepStatus     `json:"status"`
	Worktree      sql.NullString `json:"worktree"`
	AgentID       sql.NullString `json:"agent_id"`
	ClaimedAt     NullSQLiteTime `json:"claimed_at"`
	StartedAt     NullSQLiteTime `json:"started_at"`
	CompletedAt   NullSQLiteTime `json:"completed_at"`
	LastHeartbeat NullSQLiteTime `json:"last_heartbeat"`
	LastCommit    sql.NullString `json:"last_commit"`
	FilesModified sql.NullString `json:"files_modified"`
	Notes         sql.NullString `json:"notes"`
}
