// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const archiveFailedStep = `-- name: ArchiveFailedStep :exec
INSERT INTO failed_steps_history
(original_step_id, project_id, step_num, branch, scope,
 worktree, agent_id, claimed_at, started_at, failed_at,
 last_commit, files_modified, notes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'), ?, ?, ?)
`

type ArchiveFailedStepParams struct {
	OriginalStepID StepID         `json:"original_step_id"`
	ProjectID      ProjectID      `json:"project_id"`
	StepNum        int64          `json:"step_num"`
	Branch         string         `json:"branch"`
	Scope          string         `json:"scope"`
	Worktree       sql.NullString `json:"worktree"`
	AgentID        sql.NullString `json:"agent_id"`
	ClaimedAt      NullSQLiteTime `json:"claimed_at"`
	StartedAt      NullSQLiteTime `json:"started_at"`
	LastCommit     sql.NullString `json:"last_commit"`
	FilesModified  sql.NullString `json:"files_modified"`
	Notes          sql.NullString `json:"notes"`
}

func (q *Queries) ArchiveFailedStep(ctx context.Context, arg ArchiveFailedStepParams) error {
	_, err := q.db.ExecContext(ctx, archiveFailedStep,
		arg.OriginalStepID,
		arg.ProjectID,
		arg.StepNum,
		arg.Branch,
		arg.Scope,
		arg.Worktree,
		arg.AgentID,
		arg.ClaimedAt,
		arg.StartedAt,
		arg.LastCommit,
		arg.FilesModified,
		arg.Notes,
	)
	return err
}

const claimStep = `-- name: ClaimStep :one
UPDATE steps
SET status = 'claimed',
    agent_id = ?,
    claimed_at = datetime('now'),
    last_heartbeat = datetime('now')
WHERE id = (
    SELECT s.id FROM steps s
    WHERE s.project_id = (SELECT id FROM projects WHERE name = ?)
    AND s.status = 'not_started'
    AND NOT EXISTS (
        SELECT 1 FROM dependencies d
        JOIN steps ds ON d.depends_on_step_id = ds.id
        WHERE d.step_id = s.id
        AND ds.status NOT IN ('completed', 'merged')
    )
    ORDER BY s.step_num ASC
    LIMIT 1
)
RETURNING id, project_id, step_num, branch, scope, status, agent_id, claimed_at, last_heartbeat
`

type ClaimStepParams struct {
	AgentID sql.NullString `json:"agent_id"`
	Name    string         `json:"name"`
}

type ClaimStepRow struct {
	ID            StepID         `json:"id"`
	ProjectID     ProjectID      `json:"project_id"`
	StepNum       int64          `json:"step_num"`
	Branch        string         `json:"branch"`
	Scope         string         `json:"scope"`
	Status        StepStatus     `json:"status"`
	AgentID       sql.NullString `json:"agent_id"`
	ClaimedAt     NullSQLiteTime `json:"claimed_at"`
	LastHeartbeat NullSQLiteTime `json:"last_heartbeat"`
}

func (q *Queries) ClaimStep(ctx context.Context, arg ClaimStepParams) (ClaimStepRow, error) {
	row := q.db.QueryRowContext(ctx, claimStep, arg.AgentID, arg.Name)
	var i ClaimStepRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StepNum,
		&i.Branch,
		&i.Scope,
		&i.Status,
		&i.AgentID,
		&i.ClaimedAt,
		&i.LastHeartbeat,
	)
	return i, err
}

const completeStep = `-- name: CompleteStep :execresult
UPDATE steps
SET status = 'completed',
    completed_at = datetime('now'),
    last_commit = ?,
    files_modified = ?,
    notes = ?
WHERE id = ? AND status = 'in_progress'
`

type CompleteStepParams struct {
	LastCommit    sql.NullString `json:"last_commit"`
	FilesModified sql.NullString `json:"files_modified"`
	Notes         sql.NullString `json:"notes"`
	ID            StepID         `json:"id"`
}

func (q *Queries) CompleteStep(ctx context.Context, arg CompleteStepParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, completeStep,
		arg.LastCommit,
		arg.FilesModified,
		arg.Notes,
		arg.ID,
	)
}

const createDependency = `-- name: CreateDependency :execresult
INSERT INTO dependencies (step_id, depends_on_step_id)
SELECT ?, id FROM steps
WHERE project_id = ? AND step_num = ?
`

type CreateDependencyParams struct {
	StepID    StepID    `json:"step_id"`
	ProjectID ProjectID `json:"project_id"`
	StepNum   int64     `json:"step_num"`
}

func (q *Queries) CreateDependency(ctx context.Context, arg CreateDependencyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDependency, arg.StepID, arg.ProjectID, arg.StepNum)
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, base_commit, status)
VALUES (?, ?, 'active')
RETURNING id, name, base_commit, created_at, status, priority
`

type CreateProjectParams struct {
	Name       string         `json:"name"`
	BaseCommit sql.NullString `json:"base_commit"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Name, arg.BaseCommit)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCommit,
		&i.CreatedAt,
		&i.Status,
		&i.Priority,
	)
	return i, err
}

const createStep = `-- name: CreateStep :one
INSERT INTO steps (project_id, step_num, branch, scope, status)
VALUES (?, ?, ?, ?, 'not_started')
RETURNING id
`

type CreateStepParams struct {
	ProjectID ProjectID `json:"project_id"`
	StepNum   int64     `json:"step_num"`
	Branch    string    `json:"branch"`
	Scope     string    `json:"scope"`
}

func (q *Queries) CreateStep(ctx context.Context, arg CreateStepParams) (StepID, error) {
	row := q.db.QueryRowContext(ctx, createStep,
		arg.ProjectID,
		arg.StepNum,
		arg.Branch,
		arg.Scope,
	)
	var id StepID
	err := row.Scan(&id)
	return id, err
}

const failStep = `-- name: FailStep :execresult
UPDATE steps
SET status = 'failed',
    notes = ?
WHERE id = ? AND status IN ('claimed', 'in_progress')
`

type FailStepParams struct {
	Notes sql.NullString `json:"notes"`
	ID    StepID         `json:"id"`
}

func (q *Queries) FailStep(ctx context.Context, arg FailStepParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, failStep, arg.Notes, arg.ID)
}

const getAgentEventsAll = `-- name: GetAgentEventsAll :many
SELECT ae.id, ae.agent_id, ae.project_id, ae.step_id,
       ae.event_type, ae.timestamp, ae.metadata
FROM agent_events ae
ORDER BY ae.timestamp DESC
LIMIT ?
`

func (q *Queries) GetAgentEventsAll(ctx context.Context, limit int64) ([]AgentEvent, error) {
	rows, err := q.db.QueryContext(ctx, getAgentEventsAll, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentEvent{}
	for rows.Next() {
		var i AgentEvent
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ProjectID,
			&i.StepID,
			&i.EventType,
			&i.Timestamp,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgentEventsByAgent = `-- name: GetAgentEventsByAgent :many
SELECT ae.id, ae.agent_id, ae.project_id, ae.step_id,
       ae.event_type, ae.timestamp, ae.metadata
FROM agent_events ae
WHERE ae.agent_id = ?
ORDER BY ae.timestamp DESC
LIMIT ?
`

type GetAgentEventsByAgentParams struct {
	AgentID string `json:"agent_id"`
	Limit   int64  `json:"limit"`
}

func (q *Queries) GetAgentEventsByAgent(ctx context.Context, arg GetAgentEventsByAgentParams) ([]AgentEvent, error) {
	rows, err := q.db.QueryContext(ctx, getAgentEventsByAgent, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentEvent{}
	for rows.Next() {
		var i AgentEvent
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ProjectID,
			&i.StepID,
			&i.EventType,
			&i.Timestamp,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgentEventsByAgentAndProject = `-- name: GetAgentEventsByAgentAndProject :many
SELECT ae.id, ae.agent_id, ae.project_id, ae.step_id,
       ae.event_type, ae.timestamp, ae.metadata
FROM agent_events ae
LEFT JOIN projects p ON ae.project_id = p.id
WHERE ae.agent_id = ? AND p.name = ?
ORDER BY ae.timestamp DESC
LIMIT ?
`

type GetAgentEventsByAgentAndProjectParams struct {
	AgentID string `json:"agent_id"`
	Name    string `json:"name"`
	Limit   int64  `json:"limit"`
}

func (q *Queries) GetAgentEventsByAgentAndProject(ctx context.Context, arg GetAgentEventsByAgentAndProjectParams) ([]AgentEvent, error) {
	rows, err := q.db.QueryContext(ctx, getAgentEventsByAgentAndProject, arg.AgentID, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentEvent{}
	for rows.Next() {
		var i AgentEvent
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ProjectID,
			&i.StepID,
			&i.EventType,
			&i.Timestamp,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgentEventsByProject = `-- name: GetAgentEventsByProject :many
SELECT ae.id, ae.agent_id, ae.project_id, ae.step_id,
       ae.event_type, ae.timestamp, ae.metadata
FROM agent_events ae
LEFT JOIN projects p ON ae.project_id = p.id
WHERE p.name = ?
ORDER BY ae.timestamp DESC
LIMIT ?
`

type GetAgentEventsByProjectParams struct {
	Name  string `json:"name"`
	Limit int64  `json:"limit"`
}

func (q *Queries) GetAgentEventsByProject(ctx context.Context, arg GetAgentEventsByProjectParams) ([]AgentEvent, error) {
	rows, err := q.db.QueryContext(ctx, getAgentEventsByProject, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentEvent{}
	for rows.Next() {
		var i AgentEvent
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ProjectID,
			&i.StepID,
			&i.EventType,
			&i.Timestamp,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableStepsAll = `-- name: GetAvailableStepsAll :many
SELECT s.id, s.project_id, s.step_num, s.branch, s.scope, s.status,
       s.worktree, s.agent_id, s.claimed_at, s.started_at, s.completed_at,
       s.last_heartbeat, s.last_commit, s.files_modified, s.notes
FROM steps s
JOIN projects p ON s.project_id = p.id
WHERE s.status = 'not_started'
AND p.status = 'active'
AND NOT EXISTS (
    SELECT 1 FROM dependencies d
    JOIN steps ds ON d.depends_on_step_id = ds.id
    WHERE d.step_id = s.id
    AND ds.status NOT IN ('completed', 'merged')
)
ORDER BY p.priority DESC, s.step_num ASC
`

func (q *Queries) GetAvailableStepsAll(ctx context.Context) ([]Step, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableStepsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Step{}
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.StepNum,
			&i.Branch,
			&i.Scope,
			&i.Status,
			&i.Worktree,
			&i.AgentID,
			&i.ClaimedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LastHeartbeat,
			&i.LastCommit,
			&i.FilesModified,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableStepsByProject = `-- name: GetAvailableStepsByProject :many
SELECT s.id, s.project_id, s.step_num, s.branch, s.scope, s.status,
       s.worktree, s.agent_id, s.claimed_at, s.started_at, s.completed_at,
       s.last_heartbeat, s.last_commit, s.files_modified, s.notes
FROM steps s
JOIN projects p ON s.project_id = p.id
WHERE s.status = 'not_started'
AND p.status = 'active'
AND p.name = ?
AND NOT EXISTS (
    SELECT 1 FROM dependencies d
    JOIN steps ds ON d.depends_on_step_id = ds.id
    WHERE d.step_id = s.id
    AND ds.status NOT IN ('completed', 'merged')
)
ORDER BY p.priority DESC, s.step_num ASC
`

func (q *Queries) GetAvailableStepsByProject(ctx context.Context, name string) ([]Step, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableStepsByProject, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Step{}
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.StepNum,
			&i.Branch,
			&i.Scope,
			&i.Status,
			&i.Worktree,
			&i.AgentID,
			&i.ClaimedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LastHeartbeat,
			&i.LastCommit,
			&i.FilesModified,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableStepsByProjectAndScope = `-- name: GetAvailableStepsByProjectAndScope :many
SELECT s.id, s.project_id, s.step_num, s.branch, s.scope, s.status,
       s.worktree, s.agent_id, s.claimed_at, s.started_at, s.completed_at,
       s.last_heartbeat, s.last_commit, s.files_modified, s.notes
FROM steps s
JOIN projects p ON s.project_id = p.id
WHERE s.status = 'not_started'
AND p.status = 'active'
AND p.name = ?
AND s.scope = ?
AND NOT EXISTS (
    SELECT 1 FROM dependencies d
    JOIN steps ds ON d.depends_on_step_id = ds.id
    WHERE d.step_id = s.id
    AND ds.status NOT IN ('completed', 'merged')
)
ORDER BY p.priority DESC, s.step_num ASC
`

type GetAvailableStepsByProjectAndScopeParams struct {
	Name  string `json:"name"`
	Scope string `json:"scope"`
}

func (q *Queries) GetAvailableStepsByProjectAndScope(ctx context.Context, arg GetAvailableStepsByProjectAndScopeParams) ([]Step, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableStepsByProjectAndScope, arg.Name, arg.Scope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Step{}
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.StepNum,
			&i.Branch,
			&i.Scope,
			&i.Status,
			&i.Worktree,
			&i.AgentID,
			&i.ClaimedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LastHeartbeat,
			&i.LastCommit,
			&i.FilesModified,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableStepsByScope = `-- name: GetAvailableStepsByScope :many
SELECT s.id, s.project_id, s.step_num, s.branch, s.scope, s.status,
       s.worktree, s.agent_id, s.claimed_at, s.started_at, s.completed_at,
       s.last_heartbeat, s.last_commit, s.files_modified, s.notes
FROM steps s
JOIN projects p ON s.project_id = p.id
WHERE s.status = 'not_started'
AND p.status = 'active'
AND s.scope = ?
AND NOT EXISTS (
    SELECT 1 FROM dependencies d
    JOIN steps ds ON d.depends_on_step_id = ds.id
    WHERE d.step_id = s.id
    AND ds.status NOT IN ('completed', 'merged')
)
ORDER BY p.priority DESC, s.step_num ASC
`

func (q *Queries) GetAvailableStepsByScope(ctx context.Context, scope string) ([]Step, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableStepsByScope, scope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Step{}
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.StepNum,
			&i.Branch,
			&i.Scope,
			&i.Status,
			&i.Worktree,
			&i.AgentID,
			&i.ClaimedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LastHeartbeat,
			&i.LastCommit,
			&i.FilesModified,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFailedStep = `-- name: GetFailedStep :one
SELECT id, project_id, step_num, branch, scope,
       worktree, agent_id, claimed_at, started_at,
       last_commit, files_modified, notes
FROM steps
WHERE id = ? AND status = 'failed'
`

type GetFailedStepRow struct {
	ID            StepID         `json:"id"`
	ProjectID     ProjectID      `json:"project_id"`
	StepNum       int64          `json:"step_num"`
	Branch        string         `json:"branch"`
	Scope         string         `json:"scope"`
	Worktree      sql.NullString `json:"worktree"`
	AgentID       sql.NullString `json:"agent_id"`
	ClaimedAt     NullSQLiteTime `json:"claimed_at"`
	StartedAt     NullSQLiteTime `json:"started_at"`
	LastCommit    sql.NullString `json:"last_commit"`
	FilesModified sql.NullString `json:"files_modified"`
	Notes         sql.NullString `json:"notes"`
}

func (q *Queries) GetFailedStep(ctx context.Context, id StepID) (GetFailedStepRow, error) {
	row := q.db.QueryRowContext(ctx, getFailedStep, id)
	var i GetFailedStepRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StepNum,
		&i.Branch,
		&i.Scope,
		&i.Worktree,
		&i.AgentID,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.LastCommit,
		&i.FilesModified,
		&i.Notes,
	)
	return i, err
}

const getMetricsAll = `-- name: GetMetricsAll :one
SELECT
    COUNT(*) as total,
    SUM(CASE WHEN s.status IN ('completed', 'merged') THEN 1 ELSE 0 END) as completed,
    SUM(CASE WHEN s.status = 'failed' THEN 1 ELSE 0 END) as failed,
    SUM(CASE WHEN s.status IN ('claimed', 'in_progress') THEN 1 ELSE 0 END) as in_progress,
    AVG(CASE
        WHEN s.status IN ('completed', 'merged') AND s.started_at IS NOT NULL AND s.completed_at IS NOT NULL
        THEN (julianday(s.completed_at) - julianday(s.started_at)) * 24
        ELSE NULL
    END) as avg_hours
FROM steps s
JOIN projects p ON s.project_id = p.id
`

type GetMetricsAllRow struct {
	Total      int64           `json:"total"`
	Completed  sql.NullFloat64 `json:"completed"`
	Failed     sql.NullFloat64 `json:"failed"`
	InProgress sql.NullFloat64 `json:"in_progress"`
	AvgHours   sql.NullFloat64 `json:"avg_hours"`
}

func (q *Queries) GetMetricsAll(ctx context.Context) (GetMetricsAllRow, error) {
	row := q.db.QueryRowContext(ctx, getMetricsAll)
	var i GetMetricsAllRow
	err := row.Scan(
		&i.Total,
		&i.Completed,
		&i.Failed,
		&i.InProgress,
		&i.AvgHours,
	)
	return i, err
}

const getMetricsByAgent = `-- name: GetMetricsByAgent :one
SELECT
    COUNT(*) as total,
    SUM(CASE WHEN s.status IN ('completed', 'merged') THEN 1 ELSE 0 END) as completed,
    SUM(CASE WHEN s.status = 'failed' THEN 1 ELSE 0 END) as failed,
    SUM(CASE WHEN s.status IN ('claimed', 'in_progress') THEN 1 ELSE 0 END) as in_progress,
    AVG(CASE
        WHEN s.status IN ('completed', 'merged') AND s.started_at IS NOT NULL AND s.completed_at IS NOT NULL
        THEN (julianday(s.completed_at) - julianday(s.started_at)) * 24
        ELSE NULL
    END) as avg_hours
FROM steps s
JOIN projects p ON s.project_id = p.id
WHERE s.agent_id = ?
`

type GetMetricsByAgentRow struct {
	Total      int64           `json:"total"`
	Completed  sql.NullFloat64 `json:"completed"`
	Failed     sql.NullFloat64 `json:"failed"`
	InProgress sql.NullFloat64 `json:"in_progress"`
	AvgHours   sql.NullFloat64 `json:"avg_hours"`
}

func (q *Queries) GetMetricsByAgent(ctx context.Context, agentID sql.NullString) (GetMetricsByAgentRow, error) {
	row := q.db.QueryRowContext(ctx, getMetricsByAgent, agentID)
	var i GetMetricsByAgentRow
	err := row.Scan(
		&i.Total,
		&i.Completed,
		&i.Failed,
		&i.InProgress,
		&i.AvgHours,
	)
	return i, err
}

const getMetricsByProject = `-- name: GetMetricsByProject :one
SELECT
    COUNT(*) as total,
    SUM(CASE WHEN s.status IN ('completed', 'merged') THEN 1 ELSE 0 END) as completed,
    SUM(CASE WHEN s.status = 'failed' THEN 1 ELSE 0 END) as failed,
    SUM(CASE WHEN s.status IN ('claimed', 'in_progress') THEN 1 ELSE 0 END) as in_progress,
    AVG(CASE
        WHEN s.status IN ('completed', 'merged') AND s.started_at IS NOT NULL AND s.completed_at IS NOT NULL
        THEN (julianday(s.completed_at) - julianday(s.started_at)) * 24
        ELSE NULL
    END) as avg_hours
FROM steps s
JOIN projects p ON s.project_id = p.id
WHERE p.name = ?
`

type GetMetricsByProjectRow struct {
	Total      int64           `json:"total"`
	Completed  sql.NullFloat64 `json:"completed"`
	Failed     sql.NullFloat64 `json:"failed"`
	InProgress sql.NullFloat64 `json:"in_progress"`
	AvgHours   sql.NullFloat64 `json:"avg_hours"`
}

func (q *Queries) GetMetricsByProject(ctx context.Context, name string) (GetMetricsByProjectRow, error) {
	row := q.db.QueryRowContext(ctx, getMetricsByProject, name)
	var i GetMetricsByProjectRow
	err := row.Scan(
		&i.Total,
		&i.Completed,
		&i.Failed,
		&i.InProgress,
		&i.AvgHours,
	)
	return i, err
}

const getMetricsByProjectAndAgent = `-- name: GetMetricsByProjectAndAgent :one
SELECT
    COUNT(*) as total,
    SUM(CASE WHEN s.status IN ('completed', 'merged') THEN 1 ELSE 0 END) as completed,
    SUM(CASE WHEN s.status = 'failed' THEN 1 ELSE 0 END) as failed,
    SUM(CASE WHEN s.status IN ('claimed', 'in_progress') THEN 1 ELSE 0 END) as in_progress,
    AVG(CASE
        WHEN s.status IN ('completed', 'merged') AND s.started_at IS NOT NULL AND s.completed_at IS NOT NULL
        THEN (julianday(s.completed_at) - julianday(s.started_at)) * 24
        ELSE NULL
    END) as avg_hours
FROM steps s
JOIN projects p ON s.project_id = p.id
WHERE p.name = ? AND s.agent_id = ?
`

type GetMetricsByProjectAndAgentParams struct {
	Name    string         `json:"name"`
	AgentID sql.NullString `json:"agent_id"`
}

type GetMetricsByProjectAndAgentRow struct {
	Total      int64           `json:"total"`
	Completed  sql.NullFloat64 `json:"completed"`
	Failed     sql.NullFloat64 `json:"failed"`
	InProgress sql.NullFloat64 `json:"in_progress"`
	AvgHours   sql.NullFloat64 `json:"avg_hours"`
}

func (q *Queries) GetMetricsByProjectAndAgent(ctx context.Context, arg GetMetricsByProjectAndAgentParams) (GetMetricsByProjectAndAgentRow, error) {
	row := q.db.QueryRowContext(ctx, getMetricsByProjectAndAgent, arg.Name, arg.AgentID)
	var i GetMetricsByProjectAndAgentRow
	err := row.Scan(
		&i.Total,
		&i.Completed,
		&i.Failed,
		&i.InProgress,
		&i.AvgHours,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, base_commit, created_at, status, priority
FROM projects
WHERE name = ?
`

func (q *Queries) GetProject(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCommit,
		&i.CreatedAt,
		&i.Status,
		&i.Priority,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, base_commit, created_at, status, priority
FROM projects
WHERE id = ?
`

func (q *Queries) GetProjectByID(ctx context.Context, id ProjectID) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCommit,
		&i.CreatedAt,
		&i.Status,
		&i.Priority,
	)
	return i, err
}

const getScopeBreakdownAll = `-- name: GetScopeBreakdownAll :many
SELECT scope, COUNT(*) as count
FROM steps s
JOIN projects p ON s.project_id = p.id
GROUP BY scope
`

type GetScopeBreakdownAllRow struct {
	Scope string `json:"scope"`
	Count int64  `json:"count"`
}

func (q *Queries) GetScopeBreakdownAll(ctx context.Context) ([]GetScopeBreakdownAllRow, error) {
	rows, err := q.db.QueryContext(ctx, getScopeBreakdownAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetScopeBreakdownAllRow{}
	for rows.Next() {
		var i GetScopeBreakdownAllRow
		if err := rows.Scan(&i.Scope, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScopeBreakdownByAgent = `-- name: GetScopeBreakdownByAgent :many
SELECT scope, COUNT(*) as count
FROM steps s
JOIN projects p ON s.project_id = p.id
WHERE s.agent_id = ?
GROUP BY scope
`

type GetScopeBreakdownByAgentRow struct {
	Scope string `json:"scope"`
	Count int64  `json:"count"`
}

func (q *Queries) GetScopeBreakdownByAgent(ctx context.Context, agentID sql.NullString) ([]GetScopeBreakdownByAgentRow, error) {
	rows, err := q.db.QueryContext(ctx, getScopeBreakdownByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetScopeBreakdownByAgentRow{}
	for rows.Next() {
		var i GetScopeBreakdownByAgentRow
		if err := rows.Scan(&i.Scope, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScopeBreakdownByProject = `-- name: GetScopeBreakdownByProject :many
SELECT scope, COUNT(*) as count
FROM steps s
JOIN projects p ON s.project_id = p.id
WHERE p.name = ?
GROUP BY scope
`

type GetScopeBreakdownByProjectRow struct {
	Scope string `json:"scope"`
	Count int64  `json:"count"`
}

func (q *Queries) GetScopeBreakdownByProject(ctx context.Context, name string) ([]GetScopeBreakdownByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, getScopeBreakdownByProject, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetScopeBreakdownByProjectRow{}
	for rows.Next() {
		var i GetScopeBreakdownByProjectRow
		if err := rows.Scan(&i.Scope, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScopeBreakdownByProjectAndAgent = `-- name: GetScopeBreakdownByProjectAndAgent :many
SELECT scope, COUNT(*) as count
FROM steps s
JOIN projects p ON s.project_id = p.id
WHERE p.name = ? AND s.agent_id = ?
GROUP BY scope
`

type GetScopeBreakdownByProjectAndAgentParams struct {
	Name    string         `json:"name"`
	AgentID sql.NullString `json:"agent_id"`
}

type GetScopeBreakdownByProjectAndAgentRow struct {
	Scope string `json:"scope"`
	Count int64  `json:"count"`
}

func (q *Queries) GetScopeBreakdownByProjectAndAgent(ctx context.Context, arg GetScopeBreakdownByProjectAndAgentParams) ([]GetScopeBreakdownByProjectAndAgentRow, error) {
	rows, err := q.db.QueryContext(ctx, getScopeBreakdownByProjectAndAgent, arg.Name, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetScopeBreakdownByProjectAndAgentRow{}
	for rows.Next() {
		var i GetScopeBreakdownByProjectAndAgentRow
		if err := rows.Scan(&i.Scope, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStep = `-- name: GetStep :one
SELECT id, project_id, step_num, branch, scope, status,
       worktree, agent_id, claimed_at, started_at, completed_at,
       last_heartbeat, last_commit, files_modified, notes
FROM steps
WHERE id = ?
`

func (q *Queries) GetStep(ctx context.Context, id StepID) (Step, error) {
	row := q.db.QueryRowContext(ctx, getStep, id)
	var i Step
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StepNum,
		&i.Branch,
		&i.Scope,
		&i.Status,
		&i.Worktree,
		&i.AgentID,
		&i.ClaimedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastHeartbeat,
		&i.LastCommit,
		&i.FilesModified,
		&i.Notes,
	)
	return i, err
}

const insertAgentEvent = `-- name: InsertAgentEvent :exec
INSERT INTO agent_events (agent_id, project_id, step_id, event_type)
VALUES (?, ?, ?, ?)
`

type InsertAgentEventParams struct {
	AgentID   string        `json:"agent_id"`
	ProjectID NullProjectID `json:"project_id"`
	StepID    NullStepID    `json:"step_id"`
	EventType EventType     `json:"event_type"`
}

func (q *Queries) InsertAgentEvent(ctx context.Context, arg InsertAgentEventParams) error {
	_, err := q.db.ExecContext(ctx, insertAgentEvent,
		arg.AgentID,
		arg.ProjectID,
		arg.StepID,
		arg.EventType,
	)
	return err
}

const insertAgentEventFromStep = `-- name: InsertAgentEventFromStep :exec
INSERT INTO agent_events (agent_id, step_id, event_type)
SELECT s.agent_id, s.id, ? FROM steps s WHERE s.id = ?
`

type InsertAgentEventFromStepParams struct {
	EventType EventType `json:"event_type"`
	ID        StepID    `json:"id"`
}

func (q *Queries) InsertAgentEventFromStep(ctx context.Context, arg InsertAgentEventFromStepParams) error {
	_, err := q.db.ExecContext(ctx, insertAgentEventFromStep, arg.EventType, arg.ID)
	return err
}

const insertAgentEventFromStepWithMetadata = `-- name: InsertAgentEventFromStepWithMetadata :exec
INSERT INTO agent_events (agent_id, step_id, event_type, metadata)
SELECT s.agent_id, s.id, ?, ? FROM steps s WHERE s.id = ?
`

type InsertAgentEventFromStepWithMetadataParams struct {
	EventType EventType      `json:"event_type"`
	Metadata  sql.NullString `json:"metadata"`
	ID        StepID         `json:"id"`
}

func (q *Queries) InsertAgentEventFromStepWithMetadata(ctx context.Context, arg InsertAgentEventFromStepWithMetadataParams) error {
	_, err := q.db.ExecContext(ctx, insertAgentEventFromStepWithMetadata, arg.EventType, arg.Metadata, arg.ID)
	return err
}

const insertAgentEventWithMetadata = `-- name: InsertAgentEventWithMetadata :exec
INSERT INTO agent_events (agent_id, project_id, step_id, event_type, metadata)
VALUES (?, ?, ?, ?, ?)
`

type InsertAgentEventWithMetadataParams struct {
	AgentID   string         `json:"agent_id"`
	ProjectID NullProjectID  `json:"project_id"`
	StepID    NullStepID     `json:"step_id"`
	EventType EventType      `json:"event_type"`
	Metadata  sql.NullString `json:"metadata"`
}

func (q *Queries) InsertAgentEventWithMetadata(ctx context.Context, arg InsertAgentEventWithMetadataParams) error {
	_, err := q.db.ExecContext(ctx, insertAgentEventWithMetadata,
		arg.AgentID,
		arg.ProjectID,
		arg.StepID,
		arg.EventType,
		arg.Metadata,
	)
	return err
}

const listProjectsAll = `-- name: ListProjectsAll :many
SELECT id, name, base_commit, created_at, status, priority
FROM projects
ORDER BY priority DESC, created_at DESC
`

func (q *Queries) ListProjectsAll(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseCommit,
			&i.CreatedAt,
			&i.Status,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByStatus = `-- name: ListProjectsByStatus :many
SELECT id, name, base_commit, created_at, status, priority
FROM projects
WHERE status = ?
ORDER BY priority DESC, created_at DESC
`

func (q *Queries) ListProjectsByStatus(ctx context.Context, status ProjectStatus) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseCommit,
			&i.CreatedAt,
			&i.Status,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverStep = `-- name: RecoverStep :execresult
UPDATE steps
SET status = 'not_started',
    agent_id = NULL,
    claimed_at = NULL,
    started_at = NULL,
    last_heartbeat = NULL,
    worktree = NULL
WHERE id = ? AND status IN ('claimed', 'in_progress')
`

func (q *Queries) RecoverStep(ctx context.Context, id StepID) (sql.Result, error) {
	return q.db.ExecContext(ctx, recoverStep, id)
}

const resetFailedStep = `-- name: ResetFailedStep :execresult
UPDATE steps
SET status = 'not_started',
    agent_id = NULL,
    claimed_at = NULL,
    started_at = NULL,
    completed_at = NULL,
    last_heartbeat = NULL,
    last_commit = NULL,
    files_modified = NULL,
    worktree = NULL,
    notes = NULL
WHERE id = ? AND status = 'failed'
`

func (q *Queries) ResetFailedStep(ctx context.Context, id StepID) (sql.Result, error) {
	return q.db.ExecContext(ctx, resetFailedStep, id)
}

const startStep = `-- name: StartStep :execresult
UPDATE steps
SET status = 'in_progress',
    started_at = datetime('now'),
    last_heartbeat = datetime('now'),
    worktree = ?
WHERE id = ? AND status = 'claimed'
`

type StartStepParams struct {
	Worktree sql.NullString `json:"worktree"`
	ID       StepID         `json:"id"`
}

func (q *Queries) StartStep(ctx context.Context, arg StartStepParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, startStep, arg.Worktree, arg.ID)
}

const updateHeartbeat = `-- name: UpdateHeartbeat :execresult
UPDATE steps
SET last_heartbeat = datetime('now')
WHERE id = ? AND agent_id = ? AND status IN ('claimed', 'in_progress')
`

type UpdateHeartbeatParams struct {
	ID      StepID         `json:"id"`
	AgentID sql.NullString `json:"agent_id"`
}

func (q *Queries) UpdateHeartbeat(ctx context.Context, arg UpdateHeartbeatParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateHeartbeat, arg.ID, arg.AgentID)
}
